export default[

{id:"1",name:"Sony Alpha ZV-E10 Mega Pixel Interchangeable-Lens",price:"4000",image:"/public/img/product-1.png"},
{id:"21",name:"LET Play VR Plus VR HD",price:"2000",image:"/public/img/product-0.png"},
{id:"2",name:"Canon G7X  Digital SLR Camera (Black) with EF S18-55 is II Lens",price:"5000",image:"/public/img/product-2.png"},
{id:"3",name:"Adofys 70” Aluminium Camera Tripod with Travel Bag and Phone Holder",price:"500",image:"/public/img/product-3.png"},
{id:"4",name:"Sony E Mount E 55210 Mm F4.56.3 OSS Aps-C Lens (Sel55210)|Zoom Lens|Nature&Sports Photography,Black",price:"8000",image:"/public/img/product-4.png"},
{id:"5",name:"BIGXEN Telescope 60X60 HD Vision Binoculars 10000M High Power for Outdoor Hunting Optical LLL Vision Binocular",price:"800",image:"/public/img/product-5.png"},
{id:"6",name:"CASON (DEVICE OF C) Professional Telescope Binoculars with Pouch, 8 X 40 HD Vision 8 X Zoom for Adults Long Distance Bird" ,price:"900",image:"/public/img/product-6.png"},
{id:"7",name:"Canon EOS 1500D 24.1 Digital SLR Camera (Black) with EF S18-55 is II Lens",price:"7000",image:"/public/img/product-7.png"},
{id:"8", name:"Nileey-Foldable-Toy-Drone-with-HQ-WiFi-Camera-Remote-Control-for-Kids  ",price:"1300",image:"/public/img/product-8.png"},
{id:"9", name:"Drone Welko-R20-5G-GPS-positioning-Multi-function-return-home-6K-HD-Dual-camera",price:"2200",image:"/public/img/product-9.png"},
{id:"10",name:"Redmi 80 cm (32 inches) Android 11 Series HD Ready Smart LED TV | L32M6-RA/L32M7-RA (Black)",price:"25000",image:"/public/img/product-10.png"},
{id:"11",name:"Thonson TV (32 inches) Android 11 Series HD Ready Smart LED TV | L32M6-RA/L32M7-RA (Black)",price:"30000",image:"/public/img/product-11.png"},
{id:"12",name:"boAt BassHeads 100 in-Ear Wireless Headphones with Mic (Blue)",price:"1000",image:"/public/img/product-12.png"},
{id:"13",name:"JBL  Wireless EarHeadphones with Mic (Blue)",price:"999",image:"/public/img/product-13.png"},
{id:"14",name:"Sony  Wireless EarHeadphones with Mic (Blue)",price:"700",image:"/public/img/product-14.png"},
{id:"15",name:"Nitendo Switch PlayStation Console+God Of War Ragnarok | Standard Edition | PS5 Game (PlayStation 5)",price:"22000",image:"/public/img/product-15.png"},
{id:"16",name:"Fire-Boltt Gladiator 1.96 Biggest Display Luxury Stainless Steel Smart Watch",price:"900",image:"/public/img/product-16.png"},
{id:"17",name:"Dell 24 (60.96 cm) FHD Built-in Dual Speakers Monitor 1920 x 1080 Pixels at 75Hz|IPS",price:"20000",image:"/public/img/product-17.png"},
{id:"18",name:"ASUS TUF Gaming F15 (2021), 15.6 (39.62 cms) FHD 144Hz, Intel Core i5-10300H 10th Gen, GTX 1650 4GB Graphics, Gaming",price:"40000",image:"/public/img/product-18.png"},
{id:"19",name:"Acer Aspire Lite 11th Gen Intel Core i3 Premium Metal Laptop (8GB RAM/512GB SSD/Windows 11 Home) ",price:"30000",image:"/public/img/product-19.png"},
{id:"20",name:" Acer Nitro 5 Gaming Laptop AMD Ryzen™ 5 7535HS Hexa-Core Processor- (8GB/ 512 GB SSD/NVIDIA GeForce RTX 3050 4GB",price:"50000",image:"/public/img/product-20.png"},
]

// {id:"1",price:"200",image:"/public/img/cr1.jpg"},
// {id:"2",price:"200",image:"/public/img/cr2.jpg"},
// {id:"3",price:"200",image:"/public/img/cr3.jpg"},
// {id:"4",price:"200",image:"/public/img/cr4.jpg"},
// {id:"5",price:"200",image:"/public/img/cr5.jpg"},